// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FeedbackInput struct {
	Tool     string  `json:"tool"`
	Action   string  `json:"action"`
	Expected *string `json:"expected,omitempty"`
	Actual   string  `json:"actual"`
	// issue (по умолчанию) — что-то не так; praise — сработало хорошо.
	Sign *string `json:"sign,omitempty"`
}

type Mutation struct {
}

// Конверт записи/замены — тот же смысл, что у сегодняшнего REST-конверта (label/name/description/
// kind/state), state валидируется по kinds-registry вида.
type PresetInput struct {
	// Айди клиента (client-supplied-id, ROADMAP.yaml): не задан — выдаёт служба; задан — запись
	//   рождается с ним, занятый отвергается. У replacePreset обязан совпадать с айди аргумента.
	ID          *string `json:"id,omitempty"`
	Kind        string  `json:"kind"`
	Label       string  `json:"label"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	State       JSON    `json:"state"`
}

type Query struct {
}
