
import type { PassportLookup } from "../address/index.js";
import { withPassports as withPassportsOnModel, type BoundModel } from "../bound/index.js";
import { SKETCH_LAYER, SKIN_LAYER } from "../marks/index.js";
import type { Skin, SketchEdit } from "../recipe/index.js";
import { skinRules, sketchRules, type ValueVocabulary } from "../rules/index.js";
import { trace } from "../../trace/index.js";
import { darkPairs, fontText, keyframesText, layered, modeText, ruleText, variablesText } from "./print.js";
import { SkinRefused } from "./refused.js";

export { SkinRefused } from "./refused.js";

export function generateSkinCss(skin: Skin, lookup: PassportLookup, vocabulary: ValueVocabulary = {}): string {
  const done = trace(`generateSkinCss(${skin.name})`);

  const { rules, flaws } = skinRules(skin, lookup, vocabulary);
  if (flaws.length > 0) throw new SkinRefused(`skin "${skin.name}"`, flaws);

  const dark = darkPairs(skin);

  const css = layered(
    `/* Skin "${skin.name}" — generated by the skin mechanic from the record.\n` +
      "   Editing is pointless: the next generation overwrites it.\n" +
      "   Addresses are built from component anatomy, selectors are never hand-written. */",
    SKIN_LAYER,
    [...variablesText(skin, dark, lookup), fontText(), ...keyframesText(skin), ...rules.map(ruleText)],
    modeText(dark),
  );

  done();
  return css;
}

/** Тот же вход, что `generateSkinCss`, но выход — только правила и кейфреймы ОДНОГО компонента
 *  (`skin.recipes` несёт ровно одну запись), без переменных/шрифта/ответа о половине — те печатает
 *  `generateSkinCss` один раз при надевании наряда. Разбор — FAQ.md (`component-skin-on-demand`). */
export function generateComponentSkinCss(skin: Skin, lookup: PassportLookup, vocabulary: ValueVocabulary = {}): string {
  const done = trace(`generateComponentSkinCss(${skin.name})`);

  const { rules, flaws } = skinRules(skin, lookup, vocabulary);
  if (flaws.length > 0) throw new SkinRefused(`skin "${skin.name}"`, flaws);

  const css = layered(
    `/* Skin "${skin.name}" — one component, generated by the skin mechanic from the record.\n` +
      "   Editing is pointless: the next generation overwrites it.\n" +
      "   Addresses are built from component anatomy, selectors are never hand-written. */",
    SKIN_LAYER,
    [...keyframesText(skin), ...rules.map(ruleText)],
  );

  done();
  return css;
}

export function generateSketchCss(edits: readonly SketchEdit[], lookup: PassportLookup, vocabulary: ValueVocabulary = {}): string {
  const done = trace(`generateSketchCss(${edits.length})`);

  const { rules, flaws } = sketchRules(edits, lookup, vocabulary);
  if (flaws.length > 0) throw new SkinRefused("sketch edits", flaws);

  const css = layered(
    "/* Sketch edits — generated by the skin mechanic from node names.\n" +
      "   This is NOT a skin: the address here is a single place, not a coordinate, and it\n" +
      "   never ends up in the skin file. */",
    SKETCH_LAYER,
    rules.map(ruleText),
  );

  done();
  return css;
}

export interface BoundSkin extends BoundModel {
  generateSkinCss(skin: Skin, vocabulary?: ValueVocabulary): string;
  generateComponentSkinCss(skin: Skin, vocabulary?: ValueVocabulary): string;
  generateSketchCss(edits: readonly SketchEdit[], vocabulary?: ValueVocabulary): string;
}

export function withPassports(lookup: PassportLookup): BoundSkin {
  return {
    ...withPassportsOnModel(lookup),
    generateSkinCss: (skin, vocabulary) => generateSkinCss(skin, lookup, vocabulary),
    generateComponentSkinCss: (skin, vocabulary) => generateComponentSkinCss(skin, lookup, vocabulary),
    generateSketchCss: (edits, vocabulary) => generateSketchCss(edits, lookup, vocabulary),
  };
}
