package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"encoding/json"
	"fmt"
	"presets/internal/graphql/model"
	"time"
)

// ReportFeedback is the resolver for the reportFeedback field.
func (r *mutationResolver) ReportFeedback(ctx context.Context, input model.FeedbackInput) (*model.FeedbackEntry, error) {
	sign := "issue"
	if s := derefString(input.Sign); s != "" {
		sign = s
	}

	state := feedbackState{
		Tool:     input.Tool,
		Action:   input.Action,
		Expected: input.Expected,
		Actual:   input.Actual,
		Sign:     sign,
		Status:   "open",
		At:       time.Now().UTC().Format(time.RFC3339Nano),
	}
	raw, err := json.Marshal(state)
	if err != nil {
		return nil, err
	}

	entry, err := r.store.CreateFeedback(raw)
	if err != nil {
		return nil, err
	}
	return toFeedbackEntry(entry)
}

// ResolveFeedback is the resolver for the resolveFeedback field.
func (r *mutationResolver) ResolveFeedback(ctx context.Context, id string, note *string) (*model.FeedbackEntry, error) {
	entry, err := r.store.GetFeedback(id)
	if err != nil {
		return nil, err
	}
	current, err := toFeedbackEntry(entry)
	if err != nil {
		return nil, err
	}
	if current.Status == "resolved" {
		return nil, fmt.Errorf("presets: заявка %q уже разобрана", id)
	}

	next := feedbackState{
		Tool:       current.Tool,
		Action:     current.Action,
		Expected:   current.Expected,
		Actual:     current.Actual,
		Sign:       current.Sign,
		Status:     "resolved",
		At:         current.At,
		ResolvedAt: ptrString(time.Now().UTC().Format(time.RFC3339Nano)),
		Note:       note,
	}
	raw, err := json.Marshal(next)
	if err != nil {
		return nil, err
	}

	updated, err := r.store.ReplaceFeedbackState(id, raw)
	if err != nil {
		return nil, err
	}
	return toFeedbackEntry(updated)
}

// Feedback is the resolver for the feedback field.
func (r *queryResolver) Feedback(ctx context.Context, status *string, sign *string) ([]*model.FeedbackEntry, error) {
	entries, err := r.store.ListFeedback()
	if err != nil {
		return nil, err
	}

	result := make([]*model.FeedbackEntry, 0, len(entries))
	for _, entry := range entries {
		converted, err := toFeedbackEntry(entry)
		if err != nil {
			continue // испорченная/чужой формы запись пропускается, не роняет весь список
		}
		if status != nil && converted.Status != *status {
			continue
		}
		if sign != nil && converted.Sign != *sign {
			continue
		}
		result = append(result, converted)
	}
	return result, nil
}
