package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"presets/internal/graphql/generated"
	"presets/internal/graphql/loaders"
	"presets/internal/graphql/model"
	"presets/internal/kinds"

	"github.com/vikstrous/dataloadgen"
)

// CreatePreset is the resolver for the createPreset field.
func (r *mutationResolver) CreatePreset(ctx context.Context, input model.PresetInput) (model.Preset, error) {
	if err := validateState(input.Kind, input.State); err != nil {
		return nil, err
	}
	normalized, err := normalizeInput(input, r.limits)
	if err != nil {
		return nil, err
	}

	record, err := r.store.Create(normalized)
	if err != nil {
		return nil, err
	}
	return toPreset(record)
}

// ReplacePreset is the resolver for the replacePreset field.
func (r *mutationResolver) ReplacePreset(ctx context.Context, id string, input model.PresetInput) (model.Preset, error) {
	if err := validateState(input.Kind, input.State); err != nil {
		return nil, err
	}
	normalized, err := normalizeInput(input, r.limits)
	if err != nil {
		return nil, err
	}
	if normalized.ID != "" && normalized.ID != id {
		return nil, fmt.Errorf("presets: айди в конверте (%q) не тот, что у заменяемой записи (%q)", normalized.ID, id)
	}

	record, err := r.store.Replace(id, normalized)
	if err != nil {
		return nil, err
	}
	return toPreset(record)
}

// DeletePreset is the resolver for the deletePreset field.
func (r *mutationResolver) DeletePreset(ctx context.Context, id string) (bool, error) {
	return r.store.Remove(id)
}

// Palette is the resolver for the palette field.
func (r *outfitResolver) Palette(ctx context.Context, obj *model.Outfit) (*model.Palette, error) {
	if obj.PaletteName == "" {
		return nil, nil
	}
	record, err := resolveByName(ctx, "palette", obj.PaletteName)
	if err != nil || record == nil {
		return nil, err
	}
	preset, err := toPreset(record)
	if err != nil {
		return nil, err
	}
	palette, _ := preset.(*model.Palette)
	return palette, nil
}

// Forms is the resolver for the forms field.
func (r *outfitResolver) Forms(ctx context.Context, obj *model.Outfit) ([]*model.Form, error) {
	presets, err := resolveManyByName(ctx, "form", obj.FormNames)
	if err != nil {
		return nil, err
	}
	forms := make([]*model.Form, 0, len(presets))
	for _, p := range presets {
		if form, ok := p.(*model.Form); ok {
			forms = append(forms, form)
		}
	}
	return forms, nil
}

// Tags is the resolver for the tags field.
func (r *outfitResolver) Tags(ctx context.Context, obj *model.Outfit) ([]*model.Tag, error) {
	presets, err := resolveManyByName(ctx, "tag", obj.TagNames)
	if err != nil {
		return nil, err
	}
	tags := make([]*model.Tag, 0, len(presets))
	for _, p := range presets {
		if tag, ok := p.(*model.Tag); ok {
			tags = append(tags, tag)
		}
	}
	return tags, nil
}

// Presets is the resolver for the presets field.
func (r *queryResolver) Presets(ctx context.Context, kind *string, component []string, name []string) ([]model.Preset, error) {
	if kind != nil && !kinds.Known(*kind) {
		return nil, fmt.Errorf("presets: неизвестный вид %q", *kind)
	}

	metas, err := r.store.List(kind)
	if err != nil {
		return nil, err
	}

	ls := loaders.For(ctx)
	if ls == nil {
		return nil, errLoadersNotAttached
	}

	// Имя живёт в model.Meta — отбор по нему проходит ДО чтения записей: в батч едут только
	// названные, а не весь вид (presets-by-name, ROADMAP.yaml).
	wantedNames := wantedSet(name)

	ids := make([]string, 0, len(metas))
	for _, meta := range metas {
		if wantedNames != nil && (meta.Name == "" || !wantedNames[meta.Name]) {
			continue
		}
		ids = append(ids, meta.ID)
	}
	records, err := ls.Record.LoadAll(ctx, ids)
	if err := firstFatal(err); err != nil {
		return nil, err
	}

	wanted := wantedSet(component)

	presets := make([]model.Preset, 0, len(records))
	for _, record := range records {
		if record == nil {
			continue // гонка со списком: запись убрали между List и GetMany — не отказ всего запроса
		}
		preset, err := toPreset(record)
		if err != nil {
			return nil, err
		}
		if wanted != nil && !matchesComponent(preset, wanted) {
			continue
		}
		presets = append(presets, preset)
	}
	return presets, nil
}

// Preset is the resolver for the preset field.
func (r *queryResolver) Preset(ctx context.Context, id string) (model.Preset, error) {
	ls := loaders.For(ctx)
	if ls == nil {
		return nil, errLoadersNotAttached
	}

	record, err := ls.Record.Load(ctx, id)
	if err != nil {
		if errors.Is(err, dataloadgen.ErrNotFound) {
			return nil, nil // такой записи нет — null, не отказ (nullable Preset в схеме)
		}
		return nil, err
	}
	return toPreset(record)
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Outfit returns generated.OutfitResolver implementation.
func (r *Resolver) Outfit() generated.OutfitResolver { return &outfitResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	outfitResolver   struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
